embed_assets: off
javascript_compressor: closure
package_path: jammit

javascripts:
  jquery:
    - public/javascripts/jquery.js
  helper:
    - public/javascripts/helper/*.js
  plugins:
    - public/javascripts/plugins/*.js
  common:
    - public/javascripts/config.js
    - public/javascripts/pinify.js
    - public/javascripts/play.js
    - public/javascripts/playlist.js
    - public/javascripts/home.js
    - public/javascripts/player.js
    - public/javascripts/search.js
    - public/javascripts/store.js
    - public/javascripts/caching.js
    - public/javascripts/title.js
    - public/javascripts/ajax/*.js
    - public/javascripts/animations/*.js
    - public/javascripts/layout.js
stylesheets:
  common:
    - public/stylesheets/9minutes.css